#define BUTTON1 32
#define BUTTON2 33
#define BUTTON3 34
#define BUTTON_RELEASE 35
#define BUTTON1_CTRL BUTTON1 + 16
#define BUTTON2_CTRL BUTTON2 + 16
#define BUTTON3_CTRL BUTTON3 + 16
#define BUTTON_RELEASE_CTRL BUTTON_RELEASE + 16

#define BUTTON1_HOLD BUTTON1 + 32
#define BUTTON2_HOLD BUTTON2 + 32
#define BUTTON3_HOLD BUTTON3 + 32
#define BUTTON1_HOLD_CTRL BUTTON1_CTRL + 32
#define BUTTON2_HOLD_CTRL BUTTON2_CTRL + 32
#define BUTTON3_HOLD_CTRL BUTTON3_CTRL + 32

#define WHEEL_UP BUTTON1 + 64
#define WHEEL_DOWN BUTTON2 + 64
#define WHEEL_UP_CTRL BUTTON1_CTRL + 64
#define WHEEL_DOWN_CTRL BUTTON2_CTRL + 64
